/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 C:\Users\cathy\Desktop\Programs\react\updated-portfolio\src\assets\3d\deskFinal.glb 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, PerspectiveCamera, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/deskFinal.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="table">
          <group name="keycaps">
            <mesh name="key1" geometry={nodes.key1.geometry} material={materials.m_keycapWhiteBaked} />
            <mesh name="key2" geometry={nodes.key2.geometry} material={materials.m_keycapWhiteBaked} />
            <mesh name="key3" geometry={nodes.key3.geometry} material={materials.m_keycapWhiteBaked} />
            <mesh name="key4" geometry={nodes.key4.geometry} material={materials.m_keycapWhiteBaked} />
            <mesh name="key5" geometry={nodes.key5.geometry} material={materials.m_keycapWhiteBaked} />
            <mesh name="key6" geometry={nodes.key6.geometry} material={materials.m_keycapWhiteBaked} />
            <mesh name="key7" geometry={nodes.key7.geometry} material={materials.m_keycapWhiteBaked} />
            <mesh name="key8" geometry={nodes.key8.geometry} material={materials.m_keycapWhiteBaked} />
            <mesh name="key9" geometry={nodes.key9.geometry} material={materials.m_keycapWhiteBaked} />
            <mesh name="key10" geometry={nodes.key10.geometry} material={materials.m_keycapWhiteBaked} />
            <mesh name="key11" geometry={nodes.key11.geometry} material={materials.m_keycapWhiteBaked} />
            <mesh name="key12" geometry={nodes.key12.geometry} material={materials.m_keycapWhiteBaked} />
            <mesh name="key13" geometry={nodes.key13.geometry} material={materials.m_keycapWhiteBaked} />
            <mesh name="key14" geometry={nodes.key14.geometry} material={materials.m_keycapWhiteBaked} />
            <mesh name="key15" geometry={nodes.key15.geometry} material={materials.m_keycapWhiteBaked} />
            <mesh name="key16" geometry={nodes.key16.geometry} material={materials.m_keycapWhiteBaked} />
            <mesh name="key17" geometry={nodes.key17.geometry} material={materials.m_keycapWhiteBaked} />
            <mesh name="key18" geometry={nodes.key18.geometry} material={materials.m_keycapWhiteBaked} />
            <mesh name="key19" geometry={nodes.key19.geometry} material={materials.m_keycapWhiteBaked} />
            <mesh name="key20" geometry={nodes.key20.geometry} material={materials.m_keycapWhiteBaked} />
            <mesh name="key21" geometry={nodes.key21.geometry} material={materials.m_keycapWhiteBaked} />
            <mesh name="key22" geometry={nodes.key22.geometry} material={materials.m_keycapWhiteBaked} />
            <mesh name="key23" geometry={nodes.key23.geometry} material={materials.m_keycapWhiteBaked} />
            <mesh name="key24" geometry={nodes.key24.geometry} material={materials.m_keycapWhiteBaked} />
            <mesh name="key25" geometry={nodes.key25.geometry} material={materials.m_keycapWhiteBaked} />
            <mesh name="key26" geometry={nodes.key26.geometry} material={materials.m_keycapWhiteBaked} />
            <mesh name="key27" geometry={nodes.key27.geometry} material={materials.m_keycapWhiteBaked} />
            <mesh name="key28" geometry={nodes.key28.geometry} material={materials.m_keycapWhiteBaked} />
            <mesh name="key29" geometry={nodes.key29.geometry} material={materials.m_keycapWhiteBaked} />
            <mesh name="key30" geometry={nodes.key30.geometry} material={materials.m_keycapWhiteBaked} />
            <mesh name="key31" geometry={nodes.key31.geometry} material={materials.m_keycapWhiteBaked} />
            <mesh name="key32" geometry={nodes.key32.geometry} material={materials.m_keycapWhiteBaked} />
            <mesh name="key33" geometry={nodes.key33.geometry} material={materials.m_keycapWhiteBaked} />
            <mesh name="key34" geometry={nodes.key34.geometry} material={materials.m_keycapWhiteBaked} />
            <mesh name="key35" geometry={nodes.key35.geometry} material={materials.m_keycapWhiteBaked} />
            <mesh name="key36" geometry={nodes.key36.geometry} material={materials.m_keycapWhiteBaked} />
            <mesh name="key37" geometry={nodes.key37.geometry} material={materials.m_keycapWhiteBaked} />
            <mesh name="key38" geometry={nodes.key38.geometry} material={materials.m_keycapWhiteBaked} />
            <mesh name="key39" geometry={nodes.key39.geometry} material={materials.m_keycapWhiteBaked} />
            <mesh name="key40" geometry={nodes.key40.geometry} material={materials.m_keycapWhiteBaked} />
            <mesh name="key41" geometry={nodes.key41.geometry} material={materials.m_keycapWhiteBaked} />
            <mesh name="key42" geometry={nodes.key42.geometry} material={materials.m_keycapWhiteBaked} />
            <mesh name="key43" geometry={nodes.key43.geometry} material={materials.m_keycapWhiteBaked} />
            <mesh name="key44" geometry={nodes.key44.geometry} material={materials.m_keycapWhiteBaked} />
            <mesh name="key45" geometry={nodes.key45.geometry} material={materials.m_keycapWhiteBaked} />
            <mesh name="key46" geometry={nodes.key46.geometry} material={materials.m_keycapWhiteBaked} />
            <mesh name="key47" geometry={nodes.key47.geometry} material={materials.m_keycapWhiteBaked} />
            <mesh name="key48" geometry={nodes.key48.geometry} material={materials.m_keycapWhiteBaked} />
            <mesh name="key49" geometry={nodes.key49.geometry} material={materials.m_keycapWhiteBaked} />
            <mesh name="key50" geometry={nodes.key50.geometry} material={materials.m_keycapWhiteBaked} />
            <mesh name="key51" geometry={nodes.key51.geometry} material={materials.m_keycapWhiteBaked} />
            <mesh name="key52" geometry={nodes.key52.geometry} material={materials.m_keycapWhiteBaked} />
            <mesh name="key53" geometry={nodes.key53.geometry} material={materials.m_keycapWhiteBaked} />
            <mesh name="key54" geometry={nodes.key54.geometry} material={materials.m_keycapWhiteBaked} />
            <mesh name="key55" geometry={nodes.key55.geometry} material={materials.m_keycapWhiteBaked} />
            <mesh name="key56" geometry={nodes.key56.geometry} material={materials.m_keycapWhiteBaked} />
            <mesh name="key57" geometry={nodes.key57.geometry} material={materials.m_keycapWhiteBaked} />
            <mesh name="key58" geometry={nodes.key58.geometry} material={materials.m_keycapPinkBaked} position={[-56.695, 79.456, 276.885]} scale={[4.671, 2.207, 4.671]} />
            <mesh name="key59" geometry={nodes.key59.geometry} material={materials.m_keycapYellowBaked} />
            <mesh name="key60" geometry={nodes.key60.geometry} material={materials.m_keycapGreenBaked} position={[-124.057, 79.456, 267.27]} scale={[4.671, 2.207, 4.671]} />
            <mesh name="key61" geometry={nodes.key61.geometry} material={materials.m_keycapPurpleBaked} position={[-109.499, 79.456, 257.574]} scale={[4.671, 2.207, 4.671]} />
            <mesh name="key62" geometry={nodes.key62.geometry} material={materials.m_keycapBlueBaked} />
          </group>
          <mesh name="cushion" geometry={nodes.cushion.geometry} material={materials.m_cushionBaked} />
          <group name="monitor1">
            <mesh name="monitor1Shape" geometry={nodes.monitor1Shape.geometry} material={materials.m_blackFlat} />
            <mesh name="monitor1Shape_1" geometry={nodes.monitor1Shape_1.geometry} material={materials.m_whiteMonitorBaked} />
          </group>
          <group name="monitor2">
            <mesh name="monitor2Shape" geometry={nodes.monitor2Shape.geometry} material={materials.m_blackFlat} />
            <mesh name="monitor2Shape_1" geometry={nodes.monitor2Shape_1.geometry} material={materials.m_whiteMonitorBaked} />
          </group>
          <mesh name="resume" geometry={nodes.resume.geometry} material={materials.m_whitePaperBaked} />
          <mesh name="table_1" geometry={nodes.table_1.geometry} material={materials.m_tableHeadsetWhiteBaked} position={[0, 1.114, 0]} />
          <mesh name="keyboardBottom" geometry={nodes.keyboardBottom.geometry} material={materials.m_keyboardBottomBaked} position={[-90.138, 77.453, 267.842]} scale={[29.994, 18.589, 20.924]} />
          <mesh name="teacup" geometry={nodes.teacup.geometry} material={materials.m_teacupBaked} position={[-20.124, 84.674, 278.185]} rotation={[-Math.PI, 0, -Math.PI]} scale={[5.672, 6.76, 5.672]} />
        </group>
        <group name="modelsShelf">
          <group name="AnimKeys">
            <mesh name="keyRun" geometry={nodes.keyRun.geometry} material={materials.m_controlButtonsBaked} />
            <mesh name="keyWalkForward" geometry={nodes.keyWalkForward.geometry} material={materials.m_controlButtonsBaked} />
            <mesh name="keyTwoBalls" geometry={nodes.keyTwoBalls.geometry} material={materials.m_controlButtonsBaked} />
            <mesh name="keyJump" geometry={nodes.keyJump.geometry} material={materials.m_controlButtonsBaked} />
            <mesh name="keyWalkCycle" geometry={nodes.keyWalkCycle.geometry} material={materials.m_controlButtonsBaked} />
            <mesh name="keyBallBounce" geometry={nodes.keyBallBounce.geometry} material={materials.m_controlButtonsBaked} />
          </group>
          <mesh name="modelsHitbox" geometry={nodes.modelsHitbox.geometry} material={materials.m_hitbox1} position={[-389.412, 207.232, 119.528]} scale={[2.977, 112.544, 141.696]} />
          <mesh name="_modelsShelf" geometry={nodes._modelsShelf.geometry} material={materials.m_woodShelfBaked} />
          <mesh name="modelsScreen" geometry={nodes.modelsScreen.geometry} material={materials.m_digitalFrameBaked} position={[-386.894, 312.47, 26.769]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.108, 0.004, 4.959]} />
          <mesh name="flowerHitbox" geometry={nodes.flowerHitbox.geometry} material={materials.m_hitbox1} position={[-370.295, 293.418, 155.738]} scale={3.793} />
          <group name="flower">
            <mesh name="flowerShape" geometry={nodes.flowerShape.geometry} material={materials.m_lilyWater} />
            <mesh name="flowerShape_1" geometry={nodes.flowerShape_1.geometry} material={materials.m_lilyBaked} />
            <mesh name="flowerShape_2" geometry={nodes.flowerShape_2.geometry} material={materials.m_plantBroadLeafBaked} />
            <mesh name="flowerShape_3" geometry={nodes.flowerShape_3.geometry} material={materials.m_plantStemBaked} />
            <mesh name="flowerShape_4" geometry={nodes.flowerShape_4.geometry} material={materials.m_plantPotBaked} />
            <mesh name="flowerShape_5" geometry={nodes.flowerShape_5.geometry} material={materials.m_flowerLeafsBaked} />
            <mesh name="flowerShape_6" geometry={nodes.flowerShape_6.geometry} material={materials.m_flowerCenterBaked} />
            <mesh name="flowerShape_7" geometry={nodes.flowerShape_7.geometry} material={materials.m_lily1Baked} />
          </group>
          <group name="boat">
            <mesh name="boatShape" geometry={nodes.boatShape.geometry} material={materials.m_boatBaked} />
            <mesh name="boatShape_1" geometry={nodes.boatShape_1.geometry} material={materials.m_lanternHandleBaked} />
            <mesh name="boatShape_2" geometry={nodes.boatShape_2.geometry} material={materials.m_lanternBaked} />
            <mesh name="boatShape_3" geometry={nodes.boatShape_3.geometry} material={materials.m_boatRust} />
            <mesh name="boatShape_4" geometry={nodes.boatShape_4.geometry} material={materials.m_lanternGlass} />
            <mesh name="boatShape_5" geometry={nodes.boatShape_5.geometry} material={materials.m_oarBaked} />
          </group>
          <group name="egg">
            <mesh name="eggShape" geometry={nodes.eggShape.geometry} material={materials.m_dioOarBaked} />
            <mesh name="eggShape_1" geometry={nodes.eggShape_1.geometry} material={materials.m_butterflyBlueBaked} />
            <mesh name="eggShape_2" geometry={nodes.eggShape_2.geometry} material={materials.m_dioWaterBaked} />
            <mesh name="eggShape_3" geometry={nodes.eggShape_3.geometry} material={materials.m_dioLeafSmallBaked} />
            <mesh name="eggShape_4" geometry={nodes.eggShape_4.geometry} material={materials.m_dioTwigBaked} />
            <mesh name="eggShape_5" geometry={nodes.eggShape_5.geometry} material={materials.m_dioBoatBaked} />
            <mesh name="eggShape_6" geometry={nodes.eggShape_6.geometry} material={materials.m_dioGrass1Baked1} />
            <mesh name="eggShape_7" geometry={nodes.eggShape_7.geometry} material={materials.m_butterflyYellowBaked} />
            <mesh name="eggShape_8" geometry={nodes.eggShape_8.geometry} material={materials.m_dioLilyPadBaked} />
            <mesh name="eggShape_9" geometry={nodes.eggShape_9.geometry} material={materials.m_eggInsideBaked} />
            <mesh name="eggShape_10" geometry={nodes.eggShape_10.geometry} material={materials.m_dioRockBaked} />
            <mesh name="eggShape_11" geometry={nodes.eggShape_11.geometry} material={materials.m_eggShellBaked} />
            <mesh name="eggShape_12" geometry={nodes.eggShape_12.geometry} material={materials.m_dioStemBaked} />
            <mesh name="eggShape_13" geometry={nodes.eggShape_13.geometry} material={materials.m_dioLeafBigBaked1} />
            <mesh name="eggShape_14" geometry={nodes.eggShape_14.geometry} material={materials.m_eggHolderBaked} />
          </group>
          <mesh name="eggHitbox" geometry={nodes.eggHitbox.geometry} material={materials.m_hitbox1} position={[-364.516, 255.032, 25.599]} scale={0.846} />
          <group name="animPlayer">
            <mesh name="animPlayerShape" geometry={nodes.animPlayerShape.geometry} material={materials.m_animPlayerBaked} />
            <mesh name="animPlayerShape_1" geometry={nodes.animPlayerShape_1.geometry} material={materials.m_keycapYellowBaked} />
          </group>
        </group>
        <group name="artWall">
          <group name="miniPlayer">
            <group name="miniPlayer_1">
              <mesh name="miniPlayerShape" geometry={nodes.miniPlayerShape.geometry} material={materials.m_blackRubberBaked} />
              <mesh name="miniPlayerShape_1" geometry={nodes.miniPlayerShape_1.geometry} material={materials.m_blackBaked} />
              <mesh name="miniPlayerShape_2" geometry={nodes.miniPlayerShape_2.geometry} material={materials.m_miniPlayerFaceBaked} />
              <mesh name="miniPlayerShape_3" geometry={nodes.miniPlayerShape_3.geometry} material={materials.m_miniPlayerWoodBaked} />
            </group>
            <mesh name="arrowLeft" geometry={nodes.arrowLeft.geometry} material={materials.m_controlButtonsBaked} />
            <mesh name="arrowRight" geometry={nodes.arrowRight.geometry} material={materials.m_controlButtonsBaked} />
          </group>
          <mesh name="_shelf1" geometry={nodes._shelf1.geometry} material={materials.m_woodShelfBaked} position={[64.396, 212.258, 359.733]} rotation={[Math.PI / 2, 0, 0]} scale={[0.182, 0.039, 0.602]} />
          <group name="inkwell">
            <mesh name="inkwellShape" geometry={nodes.inkwellShape.geometry} material={materials.m_inkRibbonBaked} />
            <mesh name="inkwellShape_1" geometry={nodes.inkwellShape_1.geometry} material={materials.m_glass} />
            <mesh name="inkwellShape_2" geometry={nodes.inkwellShape_2.geometry} material={materials.m_inkWaxBaked} />
            <mesh name="inkwellShape_3" geometry={nodes.inkwellShape_3.geometry} material={materials.m_inkBaked} />
          </group>
          <group name="brushes">
            <mesh name="brushesShape" geometry={nodes.brushesShape.geometry} material={materials.m_paintbrushHandleBaked} />
            <mesh name="brushesShape_1" geometry={nodes.brushesShape_1.geometry} material={materials.m_paintbrushMetalGoldBaked} />
            <mesh name="brushesShape_2" geometry={nodes.brushesShape_2.geometry} material={materials.m_paintbrushMetalSilverBaked} />
            <mesh name="brushesShape_3" geometry={nodes.brushesShape_3.geometry} material={materials.m_paintbrushHairBrownBaked} />
            <mesh name="brushesShape_4" geometry={nodes.brushesShape_4.geometry} material={materials.m_paintbrushHairDarkBrownBaked} />
            <mesh name="brushesShape_5" geometry={nodes.brushesShape_5.geometry} material={materials.m_blackBaked} />
            <mesh name="brushesShape_6" geometry={nodes.brushesShape_6.geometry} material={materials.m_ceramicCupBaked} />
            <mesh name="brushesShape_7" geometry={nodes.brushesShape_7.geometry} material={materials.m_paintbrushHandleBrownBaked} />
          </group>
          <group name="tidalBasin">
            <mesh name="tidalBasinShape" geometry={nodes.tidalBasinShape.geometry} material={materials.m_blackBaked} />
            <mesh name="tidalBasinShape_1" geometry={nodes.tidalBasinShape_1.geometry} material={materials.m_artTidalBasin} />
            <mesh name="tidalBasinShape_2" geometry={nodes.tidalBasinShape_2.geometry} material={materials.m_whitePaperBaked} />
          </group>
          <group name="door">
            <mesh name="doorShape" geometry={nodes.doorShape.geometry} material={materials.m_artPaintingDoor} />
            <mesh name="doorShape_1" geometry={nodes.doorShape_1.geometry} material={materials.m_paintingFrameBaked} />
          </group>
          <group name="fruit">
            <mesh name="fruitShape" geometry={nodes.fruitShape.geometry} material={materials.m_artPaintingFruit} />
            <mesh name="fruitShape_1" geometry={nodes.fruitShape_1.geometry} material={materials.m_paintingFrameBaked} />
          </group>
          <group name="landscape">
            <mesh name="landscapeShape" geometry={nodes.landscapeShape.geometry} material={materials.m_artPaintingLandscape} />
            <mesh name="landscapeShape_1" geometry={nodes.landscapeShape_1.geometry} material={materials.m_paintingFrameBaked} />
          </group>
          <group name="birds">
            <mesh name="birdsShape" geometry={nodes.birdsShape.geometry} material={materials.m_paintingFrameBaked} />
            <mesh name="birdsShape_1" geometry={nodes.birdsShape_1.geometry} material={materials.m_artPaintingBirds} />
          </group>
          <group name="corkboard">
            <mesh name="corkboardShape" geometry={nodes.corkboardShape.geometry} material={materials.m_whiteFrameBaked} />
            <mesh name="corkboardShape_1" geometry={nodes.corkboardShape_1.geometry} material={materials.m_keycapYellowBaked} />
            <mesh name="corkboardShape_2" geometry={nodes.corkboardShape_2.geometry} material={materials.m_corkSurfaceBaked} />
          </group>
          <mesh name="businessCard" geometry={nodes.businessCard.geometry} material={materials.m_artBusinessCard} position={[133.634, 244.941, 374.941]} rotation={[Math.PI / 2, -0.031, -Math.PI]} scale={[25.739, 84.174, 14.145]} />
          <mesh name="fish" geometry={nodes.fish.geometry} material={materials.m_artDrawingFish} position={[184.242, 133.823, 373.165]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[50.416, 54.923, 71.539]} />
          <mesh name="hand" geometry={nodes.hand.geometry} material={materials.m_artDrawingHand} position={[258.045, 93.144, 373.493]} rotation={[Math.PI / 2, 0.021, Math.PI]} scale={[81.023, 81.023, 115.7]} />
          <mesh name="david" geometry={nodes.david.geometry} material={materials.m_artDrawingDavid} position={[148.119, 211.543, 375.008]} rotation={[Math.PI / 2, -0.013, -Math.PI]} scale={[50.416, 54.923, 71.539]} />
        </group>
        <group name="vrShelf">
          <group name="anivision" position={[37.445, 0, 43.159]} rotation={[0, -0.126, 0]}>
            <group name="snake" position={[-222.788, 162.804, 353.509]} rotation={[-Math.PI, 0.552, -Math.PI]} scale={1.241}>
              <primitive object={nodes.joint69} />
              <group name="snakeMesh" position={[-3.494, -131.207, 336.739]} rotation={[-Math.PI, -0.552, -Math.PI]} scale={0.806}>
                <skinnedMesh name="snakeMeshShape" geometry={nodes.snakeMeshShape.geometry} material={materials.m_snake_eyesBaked} skeleton={nodes.snakeMeshShape.skeleton} />
                <skinnedMesh name="snakeMeshShape_1" geometry={nodes.snakeMeshShape_1.geometry} material={materials.m_snakeSkinBaked} skeleton={nodes.snakeMeshShape_1.skeleton} />
              </group>
            </group>
            <group name="tarsier" position={[-32.071, 9.257, -32.657]} rotation={[0, 0.104, 0]}>
              <group name="tarsierMesh" position={[-323.004, 174.374, 298.423]} rotation={[1.452, 1.013, -1.432]} scale={25.346}>
                <mesh name="tarsierEyes" geometry={nodes.tarsierEyes.geometry} material={materials.m_TarsierEyes} position={[9.761, 1.395, 16.054]} rotation={[2.589, -1.426, -Math.PI]} scale={0.039} />
                <skinnedMesh name="tarsierBody" geometry={nodes.tarsierBody.geometry} material={materials.m_TarsierBodyBaked} skeleton={nodes.tarsierBody.skeleton} />
              </group>
              <primitive object={nodes.hips} />
            </group>
            <group name="anivisionModel" position={[-42.589, 0, -38.092]} rotation={[0, 0.126, 0]}>
              <mesh name="anivisionModelShape" geometry={nodes.anivisionModelShape.geometry} material={materials.m_mushroomBaked} />
              <mesh name="anivisionModelShape_1" geometry={nodes.anivisionModelShape_1.geometry} material={materials.m_dioramaBase} />
            </group>
          </group>
          <mesh name="vrShelfHitbox" geometry={nodes.vrShelfHitbox.geometry} material={materials.m_hitbox1} position={[-383.315, 84.175, 325.738]} scale={[7.79, 321.456, 100.227]} />
          <mesh name="vrShelf_1" geometry={nodes.vrShelf_1.geometry} material={materials.m_woodShelfBaked} />
          <mesh name="descSpaces" geometry={nodes.descSpaces.geometry} material={materials.m_descSpacesBaked} position={[-308.872, 288.354, 269.525]} rotation={[1.93, 0.338, -2.418]} scale={[65.029, 23.66, 21.305]} />
          <mesh name="descSpacesButton" geometry={nodes.descSpacesButton.geometry} material={materials.m_descSpacesButtonBaked} position={[-273.87, 239.114, 265.207]} rotation={[0.673, -0.664, 0.451]} scale={1.566} />
          <mesh name="escher" geometry={nodes.escher.geometry} material={materials.m_escherBaked} position={[-295.653, 322.289, 291.297]} rotation={[0, 1.57, Math.PI]} scale={[1.775, 1.775, -1.775]} />
          <mesh name="descAnivision" geometry={nodes.descAnivision.geometry} material={materials.m_descAnivisionBaked} position={[-309.018, 184.957, 269.937]} rotation={[1.93, 0.338, -2.418]} scale={[65.029, 23.66, 21.305]} />
          <mesh name="descAnivisionButton" geometry={nodes.descAnivisionButton.geometry} material={materials.m_descAnivisionButtonBaked} position={[-273.87, 135.326, 265.207]} rotation={[0.673, -0.664, 0.451]} scale={1.566} />
          <group name="headset">
            <mesh name="headsetShape" geometry={nodes.headsetShape.geometry} material={materials.m_headsetStrapBaked} />
            <mesh name="headsetShape_1" geometry={nodes.headsetShape_1.geometry} material={materials.m_headsetStandBaked} />
            <mesh name="headsetShape_2" geometry={nodes.headsetShape_2.geometry} material={materials.m_blackRubberBaked} />
            <mesh name="headsetShape_3" geometry={nodes.headsetShape_3.geometry} material={materials.m_tableHeadsetWhiteBaked} />
          </group>
        </group>
        <group name="architecture">
          <mesh name="wallLeft" geometry={nodes.wallLeft.geometry} material={materials.m_wallBaked} position={[16.411, 0, -794.885]} rotation={[0, -Math.PI / 2, 0]} scale={[1, 1, -1]} />
          <group name="architecture_1">
            <mesh name="architectureShape" geometry={nodes.architectureShape.geometry} material={materials.m_woodShelfBaked} />
            <mesh name="architectureShape_1" geometry={nodes.architectureShape_1.geometry} material={materials.m_rugBaked} />
            <mesh name="architectureShape_2" geometry={nodes.architectureShape_2.geometry} material={materials.m_floorBaked} />
            <mesh name="architectureShape_3" geometry={nodes.architectureShape_3.geometry} material={materials.m_wallBaked} />
          </group>
        </group>
        <PerspectiveCamera name="persp" makeDefault={false} far={10000} fov={37.849} position={[262.897, 345.586, -729.68]} rotation={[-2.988, 0.297, 3.096]}>
          <group name="__DEFAULT_LIGHT__" position={[262.897, 345.586, -729.68]} rotation={[-0.262, 0, 0]} />
        </PerspectiveCamera>
      </group>
    </group>
  )
}

useGLTF.preload('/deskFinal.glb')
